// @generated by `pnpm contracts:generate` from Rust DTOs. Do not edit manually.

export type ShareSettings = { enabled: boolean, path: string, };

export type AppSettings = { version: number, downloadShare: ShareSettings, uploadShare: ShareSettings, preferredAdapterId: string | null, port: number, maxUploadBytes: number | null, maxInboxBytes: number, maxInboxFiles: number, idleTimeoutMinutes: number | null, trustedNetworks: Array<string>, };

export type NetworkInterfaceInfo = { id: string, name: string, profileName: string, address: string, prefixLength: number, networkId: string, category: string, profileResolved: boolean, preferred: boolean, };

export type SessionInfo = { id: string, address: string, userAgent: string, createdAt: string, lastActivity: string, };

export type TransferDirection = "upload" | "download";

export type TransferState = "active" | "complete" | "cancelled" | "failed" | "expired";

export type TransferInfo = { id: string, direction: TransferDirection, name: string, transferredBytes: number, totalBytes: number, state: TransferState, updatedAt: string, };

export type ServiceState = "stopped" | "starting" | "running" | "stopping" | "error";

export type ServiceStatus = { state: ServiceState, serviceId: string | null, url: string | null, accessCode: string | null, startedAt: string | null, activeTransfers: number, sessions: Array<SessionInfo>, transfers: Array<TransferInfo>, error: string | null, };

export type FirewallStatus = { configured: boolean, programPath: string | null, port: number | null, detail: string, };

export type AppSnapshot = { appVersion: string, settings: AppSettings, configurationWarning: string | null, service: ServiceStatus, networks: Array<NetworkInterfaceInfo>, firewall: FirewallStatus, };

export type ShareValidation = { downloadError: string | null, uploadError: string | null, overlapError: string | null, };

export type SessionResponse = { serviceId: string, csrfToken: string, downloadEnabled: boolean, uploadEnabled: boolean, maxUploadBytes: number | null, };

export type DownloadEntryKind = "directory" | "file";

export type DownloadEntry = { name: string, path: string, kind: DownloadEntryKind, size: number, modifiedAt: string | null, };

export type DirectoryResponse = { path: string, query: string, entries: Array<DownloadEntry>, nextCursor: string | null, nextPage: number | null, };

export type UploadCreated = { uploadId: string, offset: number, totalBytes: number, chunkSize: number, serviceId: string, lastModified: number, };

export type CompleteResponse = { name: string, };

export type ApiError = { code: string, message: string, };
