// @generated by `pnpm contracts:generate` from Rust DTOs. Do not edit manually.

export type ShareSettings = { enabled: boolean, path: string, };

export type TrustedNetwork = { id: string, name: string, category: string, lastUsedAt: string | null, };

export type AppSettings = { version: number, downloadShare: ShareSettings, uploadShare: ShareSettings, preferredAdapterId: string | null, port: number, maxUploadBytes: number | null, maxInboxBytes: number, maxInboxFiles: number, idleTimeoutMinutes: number | null, trustedNetworks: Array<TrustedNetwork>, };

export type NetworkInterfaceInfo = { id: string, name: string, profileName: string, address: string, prefixLength: number, networkId: string, category: string, profileResolved: boolean, preferred: boolean, };

export type SessionInfo = { id: string, address: string, userAgent: string, createdAt: string, lastActivity: string, };

export type SessionChangedEvent = { "kind": "upsert", serviceId: string, session: SessionInfo, } | { "kind": "remove", serviceId: string, ids: Array<string>, } | { "kind": "reset", serviceId: string, };

export type TransferDirection = "upload" | "download";

export type TransferState = "active" | "complete" | "cancelled" | "failed" | "expired";

export type TransferInfo = { id: string, direction: TransferDirection, name: string, startedAt: string, lastProgressAt: string | null, finishedAt: string | null, transferredBytes: number, totalBytes: number, bytesPerSecond: number | null, speedSampleCount: number, state: TransferState, updatedAt: string, };

export type TransferChangedEvent = { serviceId: string, transfer: TransferInfo, };

export type ServiceState = "stopped" | "starting" | "running" | "stopping" | "error";

export type ServiceStatus = { state: ServiceState, serviceId: string | null, url: string | null, accessCode: string | null, startedAt: string | null, activeTransfers: number, sessions: Array<SessionInfo>, transfers: Array<TransferInfo>, error: string | null, };

export type FirewallStatus = { configured: boolean, programPath: string | null, port: number | null, detail: string, };

export type AppSnapshot = { appVersion: string, settings: AppSettings, configurationWarning: string | null, service: ServiceStatus, networks: Array<NetworkInterfaceInfo>, firewall: FirewallStatus, };

export type ShareValidation = { downloadError: string | null, uploadError: string | null, overlapError: string | null, };

export type SessionResponse = { serviceId: string, csrfToken: string, downloadEnabled: boolean, uploadEnabled: boolean, maxUploadBytes: number | null, };

export type DownloadEntryKind = "directory" | "file";

export type DownloadEntry = { name: string, path: string, kind: DownloadEntryKind, size: number, modifiedAt: string | null, };

export type DirectoryResponse = { path: string, query: string, entries: Array<DownloadEntry>, nextCursor: string | null, nextPage: number | null, };

export type UploadCreated = { uploadId: string, offset: number, totalBytes: number, chunkSize: number, serviceId: string, lastModified: number, };

export type CompleteResponse = { name: string, };

export type ApiError = { code: string, message: string, };

export type CommandErrorCode = "ACTIVE_TRANSFERS" | "BROAD_SHARE" | "DIAGNOSTICS_EXPORT_FAILED" | "FIREWALL_CONFIGURATION_FAILED" | "NETWORK_UNAVAILABLE" | "NETWORK_UNTRUSTED" | "SERVICE_ALREADY_RUNNING" | "SERVICE_NOT_RUNNING" | "SERVICE_START_FAILED" | "SESSION_NOT_FOUND" | "SETTINGS_INVALID" | "SETTINGS_SAVE_FAILED" | "SHARE_PREPARATION_FAILED" | "SHARE_VALIDATION_FAILED" | "UNSAVED_CHANGES";

export type CommandErrorContext = { "kind": "networkApproval", token: string, networkName: string, } | { "kind": "broadShareApproval", token: string, path: string, } | { "kind": "activeTransfers", count: number, };

export type CommandError = { code: CommandErrorCode, message: string, context: CommandErrorContext | null, };
