//! Build-only generator for the shared TypeScript contracts.

use ldtg_lib::domain::{
    network::NetworkInterfaceInfo,
    settings::{
        AppSettings, LimitSettings, NetworkSettings, ProfileOverrides, ShareProfile, ShareSettings,
        TrustedNetwork,
    },
    types::{
        AppSnapshot, CommandError, CommandErrorCode, CommandErrorContext, CompleteResponse,
        DirectoryEntry, DirectoryEntryKind, DirectoryResponse, ErrorBody, FirewallStatus,
        ServiceState, ServiceStatus, SessionChangedEvent, SessionInfo, SessionResponse,
        ShareValidation, TransferChangedEvent, TransferDirection, TransferInfo, TransferState,
        UploadResponse,
    },
};
use std::{env, error::Error, fs, path::PathBuf};
use ts_rs::TS;

const HEADER: &str =
    "// @generated by `pnpm contracts:generate` from Rust DTOs. Do not edit manually.\n\n";

fn declaration<T: TS>() -> String {
    format!("export {}", T::decl())
}

fn bindings() -> String {
    let declarations = [
        declaration::<ShareSettings>(),
        declaration::<LimitSettings>(),
        declaration::<NetworkSettings>(),
        declaration::<ProfileOverrides>(),
        declaration::<ShareProfile>(),
        declaration::<TrustedNetwork>(),
        declaration::<AppSettings>(),
        declaration::<NetworkInterfaceInfo>(),
        declaration::<SessionInfo>(),
        declaration::<SessionChangedEvent>(),
        declaration::<TransferDirection>(),
        declaration::<TransferState>(),
        declaration::<TransferInfo>(),
        declaration::<TransferChangedEvent>(),
        declaration::<ServiceState>(),
        declaration::<ServiceStatus>(),
        declaration::<FirewallStatus>(),
        declaration::<AppSnapshot>(),
        declaration::<ShareValidation>(),
        declaration::<SessionResponse>(),
        declaration::<DirectoryEntryKind>(),
        declaration::<DirectoryEntry>(),
        declaration::<DirectoryResponse>(),
        declaration::<UploadResponse>(),
        declaration::<CompleteResponse>(),
        declaration::<ErrorBody>(),
        declaration::<CommandErrorCode>(),
        declaration::<CommandErrorContext>(),
        declaration::<CommandError>(),
    ];
    format!("{HEADER}{}\n", declarations.join("\n\n"))
}

fn output_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../packages/shared/src/index.ts")
}

fn main() -> Result<(), Box<dyn Error>> {
    let mode = env::args().nth(1).unwrap_or_else(|| "--check".into());
    let output = output_path();
    let generated = bindings();
    match mode.as_str() {
        "--write" => {
            fs::write(&output, generated)?;
            println!("TypeScript-Verträge aktualisiert: {}", output.display());
        }
        "--check" => {
            let current = fs::read_to_string(&output)?;
            if current.replace("\r\n", "\n") != generated {
                return Err(format!(
                    "Die generierten TypeScript-Verträge sind veraltet. Bitte `pnpm contracts:generate` ausführen: {}",
                    output.display()
                )
                .into());
            }
            println!("Generierte TypeScript-Verträge sind aktuell.");
        }
        _ => {
            return Err(
                format!("Unbekannter Modus `{mode}`; erwartet --check oder --write.").into(),
            )
        }
    }
    Ok(())
}
